// The following directive is necessary to make the package coherent:

// +build ignore

// This program generates api for Service. It can be invoked by running
// go generate
package main

import (
	"fmt"
	"go/importer"
	"html/template"
	"os"
	"os/exec"
	"path"
	"reflect"
	"strings"

	"github.com/ianic/api_code_gen/service"
)

func Generate(svc interface{}, dtoPkgPath string) error {
	g := Generator{svc: svc, dtoPkgPath: dtoPkgPath}

	ms, err := g.findMethods()
	if err != nil {
		return err
	}
	es, err := g.findErrors()
	if err != nil {
		return err
	}

	pkg, stc := g.findNames()
	g.data = data{
		Package: pkg,
		Struct:  stc,
		Imports: []string{g.dtoPkgPath},
		Methods: ms,
		Errors:  es,
	}

	//os.MkdirAll("api", os.FileMode)
	//fn := "api_gen.go"
	//clientTemplate.Execute(os.Stdout, g.data)

	if err := g.execTemplate(clientTemplate, "api/api_gen.go"); err != nil {
		return err
	}

	fn := fmt.Sprintf("%s_gen.go", strings.ToLower(stc))
	if err := g.execTemplate(serverTemplate, fn); err != nil {
		return err
	}

	return nil
}

func (g *Generator) execTemplate(t *template.Template, fn string) error {
	os.MkdirAll(path.Dir(fn), os.ModePerm)
	f, err := os.Create(fn)
	if err != nil {
		return err
	}
	t.Execute(f, g.data)
	f.Close()
	err = exec.Command("go", "fmt", fn).Run()
	if err != nil {
		return err
	}
	return nil
}

type Generator struct {
	svc        interface{}
	dtoPkgPath string
	data       data
}

func (g *Generator) findMethods() ([]method, error) {
	v := reflect.ValueOf(g.svc)
	var ms []method
	for i := 0; i < v.NumMethod(); i++ {
		tm := v.Type().Method(i)
		m := v.Method(i)

		if m.Type().NumIn() != 1 &&
			m.Type().NumOut() != 2 &&
			m.Type().Out(1).String() != "error" {
			return nil, fmt.Errorf("unsupported signature for method %s", tm.Name)
		}

		if tm.Name == "Serve" {
			// this is generated method
			continue
		}
		ms = append(ms, method{
			Name: tm.Name,
			In:   m.Type().In(0).String(),
			Out:  m.Type().Out(0).String(),
		})
	}
	return ms, nil
}

func (g *Generator) findErrors() ([]string, error) {
	var es []string
	pkg, err := importer.Default().Import(g.dtoPkgPath)
	if err != nil {
		return nil, err
	}
	for _, n := range pkg.Scope().Names() {
		if strings.HasPrefix(n, "Err") {
			es = append(es, fmt.Sprintf("%s.%s", pkg.Name(), n))
		}
	}
	return es, nil
}

func (g *Generator) findNames() (string, string) {
	typ := reflect.TypeOf(g.svc).String()
	if strings.HasPrefix(typ, "*") {
		typ = typ[1:]
	}
	p := strings.Split(typ, ".")
	// TODO sta ako nije len = 2
	return p[0], p[1]
}

func main() {
	Generate(&service.Service{}, "github.com/ianic/api_code_gen/service/dto")
}

type data struct {
	Package string
	Struct  string
	Imports []string
	Methods []method
	Errors  []string
}

type method struct {
	Name string
	In   string
	Out  string
}

var clientTemplate = template.Must(template.New("").Parse(`// Code generated by go generate; DO NOT EDIT.
package api

import (
	"reflect"
  "errors"

	"github.com/minus5/svckit/types/registry"
{{- range .Imports }}
  "{{ . }}"
{{- end }}
)

type transport interface {
  Call(req interface{}, rsp interface{}) error
  Close()
}

type Client struct {
  t transport
}

func NewClient(r transport) *Client {
  return &Client{t: r}
}

{{- range .Methods }}

func (c *Client) {{.Name}}(req {{ .In }}) ({{ .Out }}, error) {
  rsp := &{{ .Out }}{}
  if err := c.t.Call(req, rsp); err != nil {
    return {{.Out}}{}, err
  }
  return *rsp, nil
}
{{- end }}

var (
	typeRegistry = registry.New()
)

func init() {
	typeRegistry.Add([]interface{}{
  {{- range .Methods }}
		{{ .In }}{},
  {{- end }}
	})
}

func NameFor(i interface{}) string {
	return typeRegistry.NameFor(i)
}

func TypeFor(typ string) reflect.Type {
	return typeRegistry.TypeFor(typ)
}

func ParseError(text string) error {
  if text == "" {
    return nil
  }
  switch text {
{{- range .Errors }}
  case {{ . }}.Error():
    return {{ . }}
{{- end }}
  }
  return errors.New(text)
}
`))

var serverTemplate = template.Must(template.New("").Parse(`// Code generated by go generate; DO NOT EDIT.
package {{.Package}}

import (
	"fmt"

{{- range .Imports }}
  "{{ . }}"
{{- end }}
)

func (s *{{.Struct}}) Serve(i interface{}) (interface{}, error) {
  switch req := i.(type) {
  {{- range .Methods }}
	case {{ .In }}:
    return s.{{.Name}}(req)
  {{- end }}
	default:
		return nil, fmt.Errorf("unknown type %T", req)
	}
}
`))
