// Code generated by go generate; DO NOT EDIT.
package api

import (
	"errors"
	"reflect"

	"github.com/ianic/api_code_gen/service/dto"
	"github.com/minus5/svckit/types/registry"
)

type transport interface {
	Call(req interface{}, rsp interface{}) error
	Close()
}

type Client struct {
	t transport
}

func NewClient(r transport) *Client {
	return &Client{t: r}
}

func (c *Client) Add(req dto.AddReq) (dto.AddRsp, error) {
	rsp := &dto.AddRsp{}
	if err := c.t.Call(req, rsp); err != nil {
		return dto.AddRsp{}, err
	}
	return *rsp, nil
}

func (c *Client) Multiply(req dto.MultiplyReq) (dto.MultiplyRsp, error) {
	rsp := &dto.MultiplyRsp{}
	if err := c.t.Call(req, rsp); err != nil {
		return dto.MultiplyRsp{}, err
	}
	return *rsp, nil
}

func (c *Client) Close() {
	c.t.Close()
}

var (
	typeRegistry = registry.New()
)

func init() {
	typeRegistry.Add([]interface{}{
		dto.AddReq{},
		dto.MultiplyReq{},
	})
}

func NameFor(i interface{}) string {
	return typeRegistry.NameFor(i)
}

func TypeFor(typ string) reflect.Type {
	return typeRegistry.TypeFor(typ)
}

func ParseError(text string) error {
	if text == "" {
		return nil
	}
	switch text {
	case dto.ErrOverflow.Error():
		return dto.ErrOverflow
	case dto.ErrTransport.Error():
		return dto.ErrTransport
	}
	return errors.New(text)
}
