// Code generated by go generate; DO NOT EDIT.
package api

import (
	"encoding/json"
	"github.com/ianic/api_code_gen/service/dto"
)

type transport interface {
	Call(string, []byte) ([]byte, error)
	Close()
}

type Client struct {
	t transport
}

func NewClient(r transport) *Client {
	return &Client{t: r}
}

func (c *Client) Add(req dto.TwoReq) (*dto.OneRsp, error) {
	rsp := &dto.OneRsp{}
	if err := c.call("Add", req, rsp); err != nil {
		return nil, parseError(err)
	}
	return rsp, nil
}

func (c *Client) Multiply(req dto.TwoReq) (*dto.OneRsp, error) {
	rsp := &dto.OneRsp{}
	if err := c.call("Multiply", req, rsp); err != nil {
		return nil, parseError(err)
	}
	return rsp, nil
}

func (c *Client) call(typ string, req, rsp interface{}) error {
	reqBuf, err := json.Marshal(req)
	if err != nil {
		return err
	}
	rspBuf, err := c.t.Call(typ, reqBuf)
	if err != nil {
		return err
	}
	if err := json.Unmarshal(rspBuf, rsp); err != nil {
		return err
	}
	return nil
}

func (c *Client) Close() {
	c.t.Close()
}

func parseError(err error) error {
	if err == nil {
		return nil
	}
	switch err.Error() {
	case dto.ErrOverflow.Error():
		return dto.ErrOverflow
	case dto.ErrTransport.Error():
		return dto.ErrTransport
	}
	return err
}
